apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mynginxpod
  name: mynginxpod
  namespace: pod-with-namespace
spec:
  containers:
  - image: nginx
    name: mynginxpod
    volumeMounts:
      - mountPath: "/var/app/ps"
        name: volumepv
  volumes:
      - name: volumepv
        persistentVolumeClaim:
          claimName: pvc
  dnsPolicy: ClusterFirst
  restartPolicy: Never