apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx2
  namespace: pod-with-namespace
spec:
  containers:
  - image: nginx
    name: nginx2
    args:
      - /bin/sh
      - -c
      - env;
    resources: {}
    env:
      - name: env
        valueFrom:
          configMapKeyRef:
            name: config
            key: env
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
#kubectl log nginx